### ISSUE TITLE
Community Edition integration tracker

### ISSUE THREAD

**Issue by nullsystem** [NeotokyoRevamp/neo#79]
This issue is for tracking changes to integrate CE changes (MP only) into neo. Community Edition repo: https://github.com/Nbc66/source-sdk-2013-ce

If ticked, it's integrated into the dev branch. Ordered by high to lowest priority/likely to integrate

- [ ] [H] **Update from VS2013 to VS2022 [IN PR #74]**
     - Bump minimum from SSE to SSE2
- [ ] [H] **General CE commits bug fixes [IN PR #78]**
- [ ] [H] tonysergi's changes (take from tonysergi's branch instead of CE's as CE losses commit info)
    - [ ] [H] **Part 1 - Misc. fixes [IN PR #82]**
    - [ ] [H] Part 2 - Animation jitter fixes (wait till AdamTadeusz's animations fixes/changes?)
        - https://github.com/ValveSoftware/source-sdk-2013/commit/303f58d103d2a5e4bfa03b08e4778145cce571ae
        - https://github.com/ValveSoftware/source-sdk-2013/commit/af30f28d6c1584db9e619270039cc197faaeb7a4
- [ ] [M] Update README to README.md format similar to CE
- [ ] [M] Linux symbols
     - https://github.com/Nbc66/source-sdk-2013-ce/commit/f1d69ecea3b408528ffffe3432af8d60f513488a
- [ ] [L] AnthonyPython's shader api hack
    - https://github.com/Nbc66/source-sdk-2013-ce/commit/e39cceab4fb8199a1ba7927de27069bf8b8f6883
    - https://github.com/Nbc66/source-sdk-2013-ce/commit/e458d3007b142dffa6d11458f379d2d8551457fb
- [ ] [L] Separate buggy and jalopy
    - https://github.com/Nbc66/source-sdk-2013-ce/commit/4b4c76a5fded8ae6014f93b62d6a9869e3f48b23
- [ ] [L] CE commits from JJL772, update GCC toolchains support _[maybe or maybe not use]_
- [ ] [L] JJL772 togl commits _[maybe or maybe not use]_
     - https://github.com/Nbc66/source-sdk-2013-ce/commit/95e5257971dfc5083bcf8bc45f5620788e0b4458
     - https://github.com/Nbc66/source-sdk-2013-ce/commit/0579a87934f2869a62f5f1db912df8787a696047
     - Upstream: https://github.com/ValveSoftware/ToGL/tree/master

It does not necessarily have to split by year, but it's a way to bulk some changes together. Also, the commit history has to be preserved from CE's/original authors. Commits and files that are for sp-only,  READMEs, GitHub actions/specifics, and/or unwanted won't be integrated in.
